### ISSUE TITLE
[GeoNature] Revoir le texte du formulaire de demande d’inscription

### ISSUE THREAD

**Issue by juliedelauge** [cbn-alpin/silene-geonature#100]
_"Après validation **de** l’administrateur, vous pourrez accéder aux observations publiques avec leur précision de géolocalisation maximale._:
=> Remplacer "de" par "par". Est-ce que ce sera le cas lors de la mise en production ? les données publiques seront-elles identifiées? Si non, il faudra supprimer cette phrase.

_L'accès à ces données avec leur précision maximale nécessite, dans Silene, de compléter un « formulaire de demande d’accès aux données précises » (en savoir plus)_
=> "en savoir plus" doit renvoyer à une aide pour trouver le formulaire de demande d'accès qui n'est pas très facile à trouver. Ou alors directement au formulaire?

_La géolocalisation des autres observations peut être dégradée suite à l’application des règles de **géo-confidentialité du SINP**_:
=> supprimer "geo", ajouter entre parenthèse : `(données privées et données sensibles)`. 

_La convention engage le titulaire **à un** bon usage des données et à une alimentation de Silene en retour_:
=> remplacer "à un" par "au".

**Comment by jpm-cbna** [comment]
J'ai réaliser les remplacements dans les textes pour tous les points listés.

Pour le premier point et la phrase _"Après validation de l’administrateur, vous pourrez accéder aux observations publiques avec leur précision de géolocalisation maximale."_. Est ce que rajouter le mot "disponibles", voir "identifiées et disponibles", ne suffirait pas ?
Cela donnerait : _"Après validation de l’administrateur, vous pourrez accéder aux observations publiques **identifiées et disponibles** avec leur précision de géolocalisation maximale."_
Dans tous les cas, normalement, nous devrions avoir au CBNA au moins un jeu de données avec des observations publiques...

Pour le second point, je voulais rajouter le lien vers le formulaire sur le texte "_formulaire de demande d’accès aux données précises_" qui s'affiche dans le formulaire d'inscription. Mais l'utilisateur n'est pas connecté à ce moment là car il essai de s'inscrire. Du coup, il faudrait ajouter une page explicative dans le CMS... En attendant, je supprime le lien et le texte "(en savoir plus)"...
Toutefois, un texte assez proche est présent dans l'email d'inscription envoyé à l'utilisateur et ce dernier comporte bien le lien vers le formulaire de demande d'accès.

**Comment by juliedelauge** [comment]
Ok pour moi sur les deux points

Par contre > Toutefois, un texte assez proche est présent dans l'email d'inscription envoyé à l'utilisateur et ce dernier comporte bien le lien vers le formulaire de demande d'accès.<

Quand je l’ai testé ce n’était pas le cas (me semble-t-il), il n’y avait pas de lien donc je retesterai mais c’est surement un oubli de ma part.
Julie DELAUGE

**Comment by jpm-cbna** [comment]
Je confirme que le lien est bien présent dans l'email.
