### ISSUE TITLE
 Mail reçu par le demandeur d’inscription

### ISSUE THREAD

**Issue by juliedelauge** [cbn-alpin/silene-geonature#101]
revoir un peu le texte du mail reçu par le demandeur d'une inscription 

"Nous vous rappelons que cette inscription vous donne accès à la consultation des données publiques versées dans Silene."
en fonction de ce qu'il y aura comme données publique identifiées lors de la mise en production cette phrase devra être conservées ou non .

"L’accès aux autres données nécessite de compléter un « formulaire de demande d‘accès aux données précises » (en savoir plus)." Est-ce que l’on peut mettre le lien vers le formulaire directement ? ou alors expliquer très clairement où il faut faire cette demande

**Comment by jpm-cbna** [comment]
Pour la première phrase qui peut poser problème, voir la conclusion dans le ticket #100.

Comme indiqué dans le ticket #100, le lien direct vers le formulaire a été rajouté sur le texte _« formulaire de demande d‘accès aux données précises »_ présent dans l'email reçu.
