### ISSUE TITLE
Accès au formulaire de demande d'accès aux données confidentielles

### ISSUE THREAD

**Issue by juliedelauge** [cbn-alpin/silene-geonature#102]
Comme évoqué dans d'autres tickets (retour de demande d’inscription,...)
L'accès au formulaire de demande d'accès aux données confidentielles doit être plus facile ou alors explicité.
je ne me souviens plus comment on f ait le lien entre plusieurs tickets...désolée

**Comment by jpm-cbna** [comment]
Un lien direct a été rajouté dans le texte de l'email de l'utilisateur (voir #101).

Pour le texte du formulaire d'inscription, le lien et le texte "(en savoir plus)" supprimé car il faut dans ce cas là créer une page dans le CMS présentant ce formulaire: son accès et son objectif (voir pour le suivi de cette modification le ticket #100).

Par ailleurs, un lien vers le formulaire est aussi présent dans le texte de l'introduction de la page d'accueil de Silene Expert. Je viens de faire en sorte qu'il pointe au bon endroit.
