### ISSUE TITLE
[GeoNature] Limite à 100 000 observations : message utilisateur à compléter

### ISSUE THREAD

**Issue by lvahe** [cbn-alpin/silene-geonature#115]
Dans la Synthèse, lorsque les résultats de recherche sont supérieurs à 100 000 observations, le message ci-dessous apparait :

![100000](https://user-images.githubusercontent.com/64422654/105467935-a0597880-5c96-11eb-86de-1fa8a7b35bac.png)

Est-il possible de le compléter pour indiquer aux utilisateurs comment accéder aux données ne faisant pas partie du lot des 100 000 dernières observations ?

Proposition de complément à intégrer sous le 2ème encadré jaune "En fermant cette fenêtre ..." : 
_Si vous souhaitez accéder aux données antérieures aux 100 000 dernières observations, veuillez préciser votre recherche en utilisant le filtre par date "Quand ?"._

@juliedelauge @gkapfer : Est-ce que cette formulation vous convient ?

**Comment by jpm-cbna** [comment]
J'ai rajouté le texte.
