### ISSUE TITLE
GeoNature Standard données- Nombre de digit dans champ nombre

### ISSUE THREAD

**Issue by gkapfer** [cbn-alpin/silene-geonature#120]
A moins que je me trompe: le nombre de digit est limité à 4 dans le champ nombre = va poser un souci pour certains suivis (oiseaux marins mais aussi pour un site d'hibernation de Miniotères ou on a jusque 14 000 individus en hibernation par exemple).

**Comment by jpm-cbna** [comment]
Est ce que tu peux nous préciser où se pose le problème dans l'interface ? Tu peux ajouter une impression écran.

**Comment by gkapfer** [comment]
oui pardon je pense que j'ai pas mis le bon titre... c'est dans le standard de données en fait... Je rajoute Paul qui nous avait alerté sur ce point.

**Comment by jpm-cbna** [comment]
Pour[ les champs du format d'échange](https://wiki-sinp.cbn-alpin.fr/database/import-formats#description_du_format_synthese) où il est indiqué le format `INT(4)`, le nombre 4 correspond à des bytes (=octets). Donc les champs de nombre entier sont sur 4 octets, soit des valeurs allant de -2 147 483 648 à +2 147 483 647. Voir [la doc de Postgresql sur le sujet](https://www.postgresql.org/docs/11/datatype-numeric.html).

Pour les formats de type `VARCHAR(25)`, le nombre 25 correspond à des caractères.

A noter aussi que j'ai corrigé les formats des champs `code_source` et `code_dataset` à  `VARCHAR(255)` pour qu'ils correspondent bien au format des champs correspondant dans les exports `DATASET` et `SOURCE`.
