### ISSUE TITLE
[Atlas] Icônes manquants pour 4 groupes taxonomiques

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#122]
Rubrique Galerie photos : il manque des illustrations pour 4 groupes (entognathes, algues vertes, hydrozoaires, algues rouges)

**Comment by jpm-cbna** [comment]
Les icônes ont été ajoutés sur Nature et une pull-request https://github.com/PnX-SI/GeoNature-atlas/issues/272 poussée sur le dépôt de l'Altas.
