### ISSUE TITLE
[Atlas] Lien "voir les dernières observations" non fonctionnel

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#124]
Page d'accueil, rubrique "En quelques chiffres" : lien vers « voir les dernières observations » non fonctionnel
Faire disparaître le lien

**Comment by jpm-cbna** [comment]
Le lien devrait effectivement ne pas apparaître car le paramètre d'affichage des dernières observations sur la page d'accueil est à `False`.
Par ailleurs, les requêtes SQL sont malgré tout lancé ce qui ralenti considérablement l'affichage de la page d'accueil. Il nous faut aussi supprimer le lancement de ces requêtes quand ce paramètres vaut `False`.
