### ISSUE TITLE
[CMS] Ajout chiffres rubrique données

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#133]
Rubrique « données » - paragraphe « description » : penser à ajouter les chiffres pour 
- nb de taxons, 
- nb fournisseurs flore, 
- nb observateurs, 
- pourcentage données récentes.
- -dernière ligne : donnée la plus ancienne

**Comment by lvahe** [comment]
Déjà précisé dans le ticket #68
