### ISSUE TITLE
[CMS] Rétablissement liens

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#135]
- [x] Rubrique « validation » - le lien « administrateurs de données » est censé pointer vers la page « organisation » or il pointe vers la page « données »

- [x] Rubrique "ressources" - protocole SINP : Les liens vers le protocole SINP et vers note du 2 octobre renvoient vers une page erreur

- [x] Rubrique « ressources » - rapports d’activités. Le lien vers le rapport d’activités 2019 ne fonctionne pas.

**Comment by lvahe** [comment]
Protocole SINP : le site Nature France a été refondu depuis la création de cette page ! Je ne trouve pas les nouveaux liens vers le protocole et la note du octobre 2017. Avec les annonces de fin 2020, je pense qu'il faut repenser les liens de cette rubrique.

@gkapfer je te laisse regarder pour le RA 2019.
