### ISSUE TITLE
[GeoNature]Données du futur

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#136]
Il y a des données dont la date d'observation n'est pas encore passée (décembre 2021) !
Vérifier si cela vient du jeu de données ou non.
![image](https://user-images.githubusercontent.com/61181043/110801851-eb970d00-827d-11eb-83f2-2ac063b40bc0.png)

**Comment by jpm-cbna** [comment]
54 observations botaniques ont une date dans le futur.
Pour les  trouver, choisir dans le module Synthese une date mininum au 1er mars 2021.

Ce jour un email a été envoyé avec les observations en question à Guilhem (CBNMED) pour correction...
