### ISSUE TITLE
[UsersHub]Organisme non pris en compte

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#137]
L'organisme de l'utilisateur n'est pas enregistré dans le tableau des utilisateurs alors même qu'il est renseigné dans le formulaire d'inscription

**Comment by jpm-cbna** [comment]
C'est un comportement "normal" de GeoNature.
Tous les organismes ne sont pas enregistré dans la base de données donc nous ne pouvons pas proposer de liste déroulante.
La valeur saisie par l'utilisateur peut être utilisé par l'administrateur qui valide l'inscription pour associer l'utilisateur a un organisme existant via UsersHub.
Cette tâche n'est pas obligatoire.

**Comment by juliedelauge** [comment]
Pour tant nous avons un référentiel organisme (fournisseur de données à minima) standardisé.
Ne faudrait-il pas l’utiliser pour éviter une saisie différente (orthographe ou autre) par l’utilisateur vis-à-vis des organisme cité en base de donnée
Julie



  *   De : Jean-Pascal Milcent ***@***.***>
Envoyé : jeudi 11 mars 2021 21:46
À : cbn-alpin/silene-geonature ***@***.***>
Cc : Subscribed ***@***.***>
Objet : Re: [cbn-alpin/silene-geonature] [UsersHub]Organisme non pris en compte (#137)


C'est un comportement "normal" de GeoNature.
Tous les organismes ne sont pas enregistré dans la base de données donc nous ne pouvons pas proposer de liste déroulante.
La valeur saisie par l'utilisateur peut être utilisé par l'administrateur qui valide l'inscription pour associer l'utilisateur a un organisme existant via UsersHub.
Cette tâche n'est pas obligatoire.
