### ISSUE TITLE
[Atlas] Recherche par commune non fonctionnelle page d'accueil

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#146]
Recherche par commune non fonctionnelle dans le bandeau supérieur de la page d'accueil. Lorsqu'on saisit la commune, rien ne se passe ni lorsqu'on tape sur entrée. Sur la même page d'accueil, la recherche par commune dans la rubrique "en quelques chiffres" fonctionne bien.
La recherche par commune via le bandeau supérieur fonctionne sur le reste du site, le pb se pose uniquement pour la page d'accueil

**Comment by jpm-cbna** [comment]
Je pense que les améliorations réalisées sur la page d'accueil ont résolu ce problème... À surveiller.
