### ISSUE TITLE
[GeoNature] Affichage de mailles malgré permission accordée

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#148]
J'ai une permission d'accès sur tous les départements de PACA pour la flore. Recherche par taxon -> Plantago lanceolata, sur le littoral certaines mailles s'affichent (je devrais avoir uniquement des points)
![image](https://user-images.githubusercontent.com/61181043/111609859-0405ab00-87db-11eb-88c0-d91e6be583f1.png)

**Comment by jpm-cbna** [comment]
Les observations floutées correspondent à des obs qui sont hors de la limite des contours des départements incluent dans GeoNature...

**Comment by jpm-cbna** [comment]
Résultat des requêtes:
 - obs hors des départements de PACA: **92 633**
 - obs hors du contour du territoire (= région PACA) :

**Comment by jpm-cbna** [comment]
Il ne semble pas y avoir trop de différence de performance avec l'association de toutes les obs au territoire du SINP.
La requête utilisée:
```
BEGIN;

INSERT INTO gn_synthese.cor_area_synthese (id_synthese, id_area)
    WITH sinp AS (
        SELECT id_area
        FROM ref_geo.l_areas
        WHERE id_type = ref_geo.get_id_area_type('SINP')
        LIMIT 1
    )
    SELECT
        s.id_synthese,
        sinp.id_area
    FROM gn_synthese.synthese AS s, sinp ;

COMMIT;
```

**Comment by jpm-cbna** [comment]
Donc, pour la recherche sur les 100 000 dernières observations (quand on clique sur rechercher sans paramètre):
 - avant ajout des 9,3 millions de correspondance entre les observations et le territoire SINP: **43s**
 - après: **47s**
Tous les obs sont bien accessibles maintenant
![Screenshot_20210318_184341](https://user-images.githubusercontent.com/51449363/111672065-dd1a9980-8819-11eb-90ca-fe24aa9341ea.png)
:
