### ISSUE TITLE
Filtre communal ne fonctionne pas

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#15]
Le filtre communal fonctionnait hier mais ne fonctionne plus

**Comment by jpm-cbna** [comment]
Peux tu préciser ce qu'il se passe ou pas ? De mon côté, cela fonctionne.
Essaye de cliquer sur l'icône rouge de poubelle dans la colonne des filtres pour réinitialiser ta recherche.

**Comment by okristo** [comment]
Re-testé aujourd'hui, ça fonctionne
