### ISSUE TITLE
[GeoNature] Commanditaire formulaire demande d’accès aux données et convention

### ISSUE THREAD

**Issue by juliedelauge** [cbn-alpin/silene-geonature#150]
Dans le formulaire, nous demandons le commanditaire (=> ok).
Par contre ce qui est saisi dans ce champ est repris dans la convention comme l'organisme du demandeur ce qui n'est pas la même chose.
Là ou figure commanditaire c'est l’organisme du demandeur qui doit figurer.

**Comment by okristo** [comment]
Le commanditaire apparaît dans la 1ère ligne de la convention. Pas indispensable de le remettre dans l'article 2. 
Dans l'article 2, supprimer le commanditaire et le remplacer par l'organisme de l'utilisateur (si possible et si renseigné lors de la création de compte)

**Comment by juliedelauge** [comment]
Ce n’est pas le nom du commanditaire qui est attendu dans la convention ni en intro ni en article 2 mais celui de l’organisme du demandeur


[cid:564d6165-6681-4ef6-ac7e-9db424007842]<http://www.cen-paca.org/index.php?rub=0>​

 [cid:30ce1ba6-cf9d-4098-bcd0-1af0a5508258] <https://www.facebook.com/CENPACA/>   [cid:a68c290e-8b4d-4f64-b1c6-e438422bdc67] <https://www.instagram.com/cen_paca/?hl=fr>
Julie DELAUGE
Adjointe à la Direction –
Responsable Connaissance et Programmes
Conservatoire d'espaces naturels de Provence-Alpes-Côte d'Azur
18 avenue du Gand – 04200 Sisteron
Tél. 04 92 34 40 10
***@***.*** - www.cen-paca.org<http://www.cen-paca.org>

[cid:e8790ea2-a3b9-460d-a37a-9d6d61750590]<https://www.helloasso.com/associations/conservatoire-d-espaces-naturels-de-provence-alpes-cote-d-azur/adhesions/adhesion-2021-au-conservatoire-d-espaces-naturels-de-provence-alpes-cote-d-azur>


De : okristo ***@***.***>
Envoyé : vendredi 19 mars 2021 11:18
À : cbn-alpin/silene-geonature ***@***.***>
Cc : Julie Delauge ***@***.***>; Author ***@***.***>
Objet : Re: [cbn-alpin/silene-geonature] [GeoNature] Commanditaire formulaire demande d'accés aux données et convention (#150)


Le commanditaire apparaît dans la 1ère ligne de la convention. Pas indispensable de le remettre dans l'article 2.
Dans l'article 2, supprimer le commanditaire et le remplacer par l'organisme de l'utilisateur (si possible et si renseigné lors de la création de compte)

**Comment by jpm-cbna** [comment]
La récupération des informations de l'organisme saisie par l'utilisateur dans le formulaire d'inscription n'est pas simple à l'heure actuelle. Du coup, nous allons ajouter un champ "Organisme" supplémentaire dans le formulaire de demande d'accès aux données précises. Le contenu de ce champ sera utilisé dans le texte de la convention à la place du nom du commanditaire.

Exemple du rendu du formulaire de demande d'accès:
![Screenshot_20210322_121317](https://user-images.githubusercontent.com/51449363/111987544-a55c6c00-8b0f-11eb-825d-3cfa420f9543.png)
