### ISSUE TITLE
[GeoNature] Modification mail d'information demande de création compte GeoNature

### ISSUE THREAD

**Issue by lvahe** [cbn-alpin/silene-geonature#151]
Dans le mail qui est envoyé aux administrateurs suite à une demande de création de compte sur Silene Expert, il faudrait : 

- [x] ajouter l'organisme renseigné par la personne qui fait la demande dans le corps du mail : Nom, Prénom, **Organisme**, Identifiant, Email
- [x] modifier le lien hypertexte sous l'intitulé "Pour valider cette demande, _cliquer sur ce lien_" afin d'arriver sur UserHub et non pas sur Silene Admin dans GeoNature.

**Comment by jpm-cbna** [comment]
Alors pour le lien c'est normal qu'il pointe vers GeoNature car c'est pour valider l'inscription. Pas pour accéder à Usershubs...
Usershubs n'est pas forcément installé avec GeoNature, du coup, il faut voir s'il existe un paramètre permettant de voir si Usershub existe...

Pour l'organisme, il devrait être présente avec les infos du champ Remarques. Je regarde qu'elle est le problème.

**Comment by okristo** [comment]
Ajouts à apporter dans le mail de validation de création de compte.
"Nous vous rappelons que cette inscription vous donne accès à la consultation des données publiques versées dans Silene.
L’accès aux autres données nécessite de compléter un « formulaire de demande d‘accès aux données précises » **disponible via l'onglet "Demande accès données précises" dans SILENE Expert. [Ajouter le lien sur "demande accès données précises]**
L'accord sera formalisé par l’acceptation d'une convention « droit d'accès aux données précises » et donnera lieu à l'attribution d'un accès direct à ces données. **[Ajouter sur "convention" le lien vers la convention type intégrée dans le CMS]**
La convention engage le titulaire à un bon usage des données et à une alimentation de Silene en retour."
