### ISSUE TITLE
[GeoNature] Demande d'accès : texte mails

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#156]
Remplacer "aucun" par "tous" dans le champ "groupes taxonomiques" dans le mail envoyé aux administrateurs pour prévenir de la demande d'accès et dans le mail envoyé à l'utilisateur pour lui signifier la réponse à sa demande

**Comment by jpm-cbna** [comment]
Je pense que simplement remplace "Aucun" par "Tous" ne conviendra pas. Il faut revoir la formulation.

**Comment by okristo** [comment]
Dans le mail que reçoivent les admin pour une demande d'accès :
"Limitation de l'accès
Cet accès sera limité aux :
Entités géographiques : Hautes-Alpes [05] ; Bouches-du-Rhône [13].
Groupes taxonomiques : Aucun." **Remplacer Aucun par Tous**

Dans le mail d'acceptation de la demande que reçoit l'utilisateur : 
"Votre accès est limité aux :
entités géographiques : Hautes-Alpes [05].
groupes taxonomiques : Aucun." **Remplacer Aucun par Tous**
Idem pour le mail reçu par l'utilisateur en cas de refus ou de mise en attente
Selon moi, on peut remplacer aucun par tous.

**Comment by okristo** [comment]
Une coquille dans les demandes d'accès : remplacer "privés" par "privées".
Dans les mails reçus par l'utilisateur pour statuer sur sa demande d'accès (confirmation, mise en attente et refus) : dans le 1er paragraphe, remplacer "demande de permissions d'accès" par "demande d'accès"

**Comment by jpm-cbna** [comment]
Dans l'email de remise en attente, ajouté un "e" à "replacés" (=> "replacées").

**Comment by jpm-cbna** [comment]
Corrigé dans la branche feat/permission de GN.
