### ISSUE TITLE
Tous les outils : remplacement logo DREAL PACA

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#157]
Remplacer le logo de la DREAL PACA : 
- dans la frise pied de page du CMS
- Dans SILENE Expert
- Dans SILENE Nature
![pref_region_provence_alpes_cote_d_azur_cmjn_cle07bcf1](https://user-images.githubusercontent.com/61181043/111982778-ab4f4e80-8b09-11eb-8f2d-978e7e62cb2b.jpg)

**Comment by jpm-cbna** [comment]
Pour[ la frise du CMS](https://cms.silene.eu/wp-content/uploads/2020/11/bottom_cms_logos.png), je n'ai pas le fichier d'origine qui a permis de la créer. Je peux essayer de remplacer le logo dans le fichier actuel mais cela risque de ne pas être terrible.
C'est Paul du CEN qui l'a intégré, je suppose que c'est peut être Sonia qui lui a transmis ? @gkapfer Peux tu nous dire ce qu'il en est ?

**Comment by jpm-cbna** [comment]
Finalement, je me suis débrouillé, j'ai modifié les 3 images présentent sur le CMS. Elles étaient assez grande pour les retravailler.
