### ISSUE TITLE
Référentiel taxonomique absent

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#16]
Aucun taxon trouvé lorsqu'on saisit une donnée "aucun taxon trouvé pour cette recherche"
![saisie_taxon](https://user-images.githubusercontent.com/61181043/74731436-3f385200-5248-11ea-83c3-ff43ca88d791.jpg)

**Comment by jpm-cbna** [comment]
Ok, c'est normal. Je n'ai pas du tout configuré OccTax.
De mémoire, il est nécessaire de créer une liste de taxon dans TaxHub.
Je regarde pour rendre le module fonctionnel.
