### ISSUE TITLE
Atlas : bloquer l'accès aux données précises

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#17]
Se limiter à un affichage par maille. En gardant la possibilité de supprimer ce blocage à moyen terme.

**Comment by jpm-cbna** [comment]
Ok, je regarde pour configurer l'affichage de l'Atlas avec des mailles uniquement.

**Comment by jpm-cbna** [comment]
L'affichage est maintenant au format maille 5x5km comme prévu dans le cahier des charges de l'étude de préfiguration.
Toutefois, à noter que l'affichage sur la carte de la fiche par commune n'est plus vraiment intéressant : https://nature.silene.eu/commune/05148 (cliquer sur une ligne dans la liste des taxons pour voir).
La maille correspond à la taille de la commune... Il est possible d'utiliser des mailles de 1x1km et il est relativement facile de faire le changement pour tester...
