### ISSUE TITLE
[GeoNature] : améliorer l'affichage dans la synthèse

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#181]
Affichage par maille à petite échelle. 
Voir détails : https://github.com/PnX-SI/GeoNature/issues/1093

**Comment by jpm-cbna** [comment]
Voir aussi le document de synthèse sur le wiki : https://wiki-sinp.cbn-alpin.fr/fonctionnalites/geonature/synthese-regroupement-par-mailles

**Comment by jpm-cbna** [comment]
Pour moi, c'est bon, c'est en place.
