### ISSUE TITLE
[GeoNature] : données hors PACA

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#184]
Une donnée repérable facilement hors PACA (puisque localisée en Afrique).
UUID = 32806af8-169b-426f-aaf5-d19fcfdd0048
Supprimer la donnée et prévenir l'admin de données concerné

**Comment by jpm-cbna** [comment]
Je relance [les scripts qui nettoient les données hors PACA](https://github.com/cbn-alpin/sinp-paca-data/tree/master/outside/data/sql/update).
