### ISSUE TITLE
[GeoNature] : affichage alerte 100 000 données

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#185]
Suite à la mise à jour du 25/03, la fenêtre d'alerte présentant la limite de 100 000 données ne s'affiche plus.
A ajouter

**Comment by jpm-cbna** [comment]
Résolut par le commit [613f33a06](https://github.com/PnX-SI/GeoNature/commit/613f33a060dd15bae9a59b75ef386402e61cb849).
