### ISSUE TITLE
[GeoNature] : taille police filtre taxon

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#186]
Possible de diminuer un peu la police du filtre taxon ?
En l'état, le texte d'implémentation est peu lisible 
![image](https://user-images.githubusercontent.com/61181043/160243067-57cd860a-20d5-4410-a3bc-685c22e6ee4a.png)

**Comment by jpm-cbna** [comment]
Le taille de la police a été diminuée et le liste de nom affichée au dessus des autres composants dans le commit [7eaa6de](https://github.com/PnX-SI/GeoNature/commit/7eaa6decdcc36d16c7677a94aa0566237fe6f807).
![Screenshot_20220327_222154](https://user-images.githubusercontent.com/51449363/160299378-b9052d53-97b5-4850-80ae-8ba442fc2240.png)
