### ISSUE TITLE
[GeoNature] : dessin de rectangle

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#187]
L'outil rectangle fonctionne mal. Lorsqu'on sélectionne l'outil et que l'on commence à tracer un rectangle, celui-ci reste tout petit.
RAS pour polygone et cercle

**Comment by jpm-cbna** [comment]
C'est un bug de la lib leaflet.draw qui ne semble plus maintenue.
Il y a quand même une PR qui corrige le problème. J'ai donc appliquer la correction manuellement en suivant les indications que j'ai renseigné dans le ticket [#1802](https://github.com/PnX-SI/GeoNature/issues/1802) de GeoNature.
