### ISSUE TITLE
[GeoNature] : infos manquantes convention accès

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#188]
Convention d'accès qui s'ouvre lorsqu'on clique sur envoyer dans le formulaire de demande d'accès.
Dans l'article 2, les entrées correspondant aux territoires géo sélectionnés dans le formulaire ne s'affichent pas délimitation géographique) : 
![image](https://user-images.githubusercontent.com/61181043/160243753-164fb1b2-7979-46d3-9af0-2f94492ad141.png)

**Comment by jpm-cbna** [comment]
Le même problème se posait aussi pour l'affichage des groupes systématiques sélectionnés. Corrigé dans les commits [3bade7c](https://github.com/PnX-SI/GeoNature/commit/3bade7c884baae1cc37bba212fc78b8616041f33), [3c3753c](https://github.com/PnX-SI/GeoNature/commit/3c3753c447c447dc1124b8652cc42d27be2179ff) et [86ea41a](https://github.com/PnX-SI/GeoNature/commit/86ea41a9a3d542dddd5b6f6d3da1d1aa6342e0fc).
