### ISSUE TITLE
[Atlas] : problème affichage pied de page

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#189]
Recherche par espèce
Le pied de page (comportant notamment les logos) s'affiche sous la carte de répartition. Le problème se pose sur Chrome, pas sur Firefox.
Ex : Himantoglossum robertianum
![image](https://user-images.githubusercontent.com/61181043/160342738-ad63cb98-c832-4659-ba65-4cdfa4fa15d5.png)

**Comment by jpm-cbna** [comment]
@okristo Est ce que tu peux tester à nouveau (avec un` CTRL-MAJ+R`) car je n'ai pas le problème sous Chrome.
Je pense aussi avoir rajouté une règle CSS qui évite ce problème...

**Comment by okristo** [comment]
OK, le problème ne se pose plus depuis mon PC du bureau. Je testerai à nouveau depuis chez moi (j'avais identifié le pbm avec mon ordi perso).
