### ISSUE TITLE
[GeoNature] : message d'erreur page de connexion

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#190]
Un message d'erreur apparaît sur la page de connexion. Il n'empêche pas la connexion. Valable pour Chrome et Firefox
![image](https://user-images.githubusercontent.com/61181043/160343348-9d169303-bd56-4448-93a6-3d9ffdcd6be2.png)

**Comment by okristo** [comment]
Ce bug n'empêche pas la connexion mais empêche la réinitialisation du mot de passe

**Comment by jpm-cbna** [comment]
> Ce bug n'empêche pas la connexion mais empêche la réinitialisation du mot de passe

En fait, je reçois bien un email quand je demande le renouvellement de mon mot de passe.
Quand je clique sur le lien dans l'email pour saisir un nouveau mot de passe, je n'arrive pas sur la page de changement de mot de passe mais sur la page de login.
Par contre, si je copie le lien dans l'email et que je le colle dans la zone d'URL de mon navigateur cela fonctionne...
