### ISSUE TITLE
[GeoNature] Fichier "taxons" : lignes en double

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#193]
Dans le fichier "Taxons", certaines lignes apparaissent en double. ça ne devrait pas être le cas.
Ex dans le fichier ci-dessous (cd_ref = 97609 ou encore 134411 ou 99373)
[synthese_taxons_2022-06-20T13_45_30.361Z.csv](https://github.com/cbn-alpin/sinp-paca-tickets/files/8941191/synthese_taxons_2022-06-20T13_45_30.361Z.csv)

**Comment by jpm-cbna** [comment]
Corrigé dans la branche feat/sinp et en production.
