### ISSUE TITLE
[Usershub] : un message d'erreur s'affiche lors de l'acceptation d'une création de compte

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#195]
Dans Usershub, onglet demande de compte en cours, lorsqu'on clique sur la coche verte pour valider une création de compte, un message d'erreur apparaît. Il n'a visiblement aucun impact. Pas pu faire une impression d'écran à ce stade.
A priori l'envoi d'e-mail de confirmation de création de compte ne fonctionne pas. Lié au message d'erreur ?

**Comment by helenechauvin** [comment]
voici le message d'erreur qui s'affiche quand on valide un compte
![image](https://user-images.githubusercontent.com/105280926/174766734-3f025c5a-5188-4fb9-96e4-9d4b30bded99.png)

**Comment by jpm-cbna** [comment]
Corrigé dans le commit https://github.com/PnX-SI/GeoNature/commit/a0e8f942acd6f4478017bef521cb97eb5fa3ebf7
