### ISSUE TITLE
Problème import geojson

### ISSUE THREAD

**Issue by jmg-cbna** [cbn-alpin/silene-geonature#20]
Problème d'import du geojson. Pour le kml ça marche.

{
"type": "FeatureCollection",
"name": "test_gn",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::2154" } },
"features": [
{ "type": "Feature", "properties": { }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 955613.922484700800851, 6379846.638959590345621 ], [ 951873.692470044596121, 6380340.273377767764032 ], [ 950392.789215510711074, 6379941.568655393086374 ], [ 950601.634546278277412, 6378916.327940716408193 ], [ 951664.847139277029783, 6378308.777887574397027 ], [ 953411.55354206066113, 6378061.960678485222161 ], [ 955613.922484700800851, 6378194.862252609804273 ], [ 956449.303807771182619, 6378346.749765895307064 ], [ 956658.149138538748957, 6379068.215454001910985 ], [ 956791.050712663680315, 6379561.849872179329395 ], [ 955613.922484700800851, 6379846.638959590345621 ] ] ] } }
]
}

**Comment by jpm-cbna** [comment]
Effectivement, le fichier geojson en question ne fonctionne pas.
Au niveau des interfaces web, il faut utiliser du GeoJson tel qu'il est décrit dans la RFC 7946. Du coup, par rapport au fichier que tu utilises, il y a plusieurs problèmes que l'on peut corriger ainsi :
 - utiliser le SCR ESPG::4326 (= WGS84)
 - utiliser des coordonnées en latitude longitude décimales
 - éventuellement supprimer l'entrée "crs" dans le GeoJson car ce n'est plus compatible avec les versions récentes du standard (voir  https://tools.ietf.org/html/rfc7946#section-4 ). Ceci dit GeoNature accepte la présence de cet attribut.

Pour cela, le plus simple est de charger dans QGIS l'ancien fichier et l'enregistrer à nouveau en GeoJson avec: 
-  Format: GeoJson
-  SCR : ESPG::4326 (= WGS84)
- Encodage: UTF-8

Cela donne un fichier ressemblant à ceci qui fonctionne sous GeoNature:
```
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 6.21438970085511, 44.470843946978455 ], [ 6.16765535792024, 44.476644331694281 ], [ 6.148850925306411, 44.473591101698538 ], [ 6.15096028502704, 44.464294212820846 ], [ 6.164008467618633, 44.458446798124172 ], [ 6.185819731361772, 44.455594696128557 ], [ 6.213544832255963, 44.455986943889933 ], [ 6.224113411310671, 44.457046633095551 ], [ 6.227106609299824, 44.463459073258647 ], [ 6.229029465726309, 44.46785017339699 ], [ 6.21438970085511, 44.470843946978455 ] ] ] } }
]
}
```
