### ISSUE TITLE
[Geonature] Problème de connexion - compte Silene Expert

### ISSUE THREAD

**Issue by helenechauvin** [cbn-alpin/silene-geonature#200]
Plusieurs utilisateurs rencontrent ce message d'erreur lorsqu'ils essaient de se connecter à leurcompte. La modification du mot de passe ne change rien, la connexion échoue.
![image](https://user-images.githubusercontent.com/105280926/176199913-42499765-fb9d-4573-93d4-d380b8efb9eb.png)

**Comment by jpm-cbna** [comment]
C'est difficile de savoir qu'elle est le problème.
J'ai tester la connexion qui fonctionne sur plusieurs comptes distincts.
Apparemment, l'impression écran provient d'un smartphone.
Est ce que l'utilisateur peut tester à nouveau depuis un navigateur (Chrome, Firefox) d'un ordinateur ?

**Comment by helenechauvin** [comment]
Un des deux utilisateurs utilisait Safari, elle refait le test et voit si ça fonctionne. Par contre le second utilisateur a testé avec firefox et ça ne fonctionne toujours pas.

**Comment by helenechauvin** [comment]
Une utilisatrice n'arrive pas à se connecter à son compte Silene, malgrè plusieurs tentatives de modification de mot de passe (j'ai vérifié, elle utilise le bon identifiant). Il s'agit du compte 219 (Laura Granato).
![image](https://user-images.githubusercontent.com/105280926/216574265-8ce33969-e984-4cb9-842a-768219f4b1c9.png)

**Comment by jpm-cbna** [comment]
Le problème semble lié à la présence d'un espace à la fin des identifiants des utilisateurs en question !

Pour résoudre le problème, il suffit de supprimer l'espace dans l'identifiant via UsersHub.
