### ISSUE TITLE
[GeoNature] Recherche taxonomique avancée ne fonctionne plus sur Silene Expert

### ISSUE THREAD

**Issue by helenechauvin** [cbn-alpin/silene-geonature#212]
Depuis hier, il semble y avoir un problème sur la recherche taxonomique avancée. Un message d'erreur apparaît "0-Unknow error undefined id requete: undefined" lorsqu'on tente de saisir un taxon.
![image](https://user-images.githubusercontent.com/105280926/203505477-65a978ed-8a99-4e16-b67f-1255b7697ac4.png)

**Comment by jpm-cbna** [comment]
Le problème vient du service systemd "taxhub" qui s'est arrêté à cause d'un problème de connexion avec la base de données:
```
psycopg2.OperationalError: could not connect to server: No route to host
    Is the server running on host "10.0.1.20" and accepting
    TCP/IP connections on port 5432?
```
Nous avions déjà eu un souci similaire avec le service de l'Atlas.
A priori, j'ai l'impression que depuis fin août, ce genre de problème survient. C'est peut être lié au VPN car le message "`No route to host`" semble indiqué que l'IP `10.0.1.20` du VPN n'est plus accessible...

En attendant, j'ai mis en place des tentatives de redémarrage automatique du service dans les fichiers "override.conf" de tous les services GeoNature:
```properties
[Unit]
StartLimitIntervalSec=6min
StartLimitBurst=5

[Service]
ExecStart=
ExecStart=<commande spécifique au service >
Restart=on-failure
RestartSec=1min
```

**Comment by helenechauvin** [comment]
merci. En effet ça semble refonctionner, sauf que ça a engendré d'autres bugs : les menus déroulants des statuts et listes rouges ont disparu et il n'est donc plus possible de requêter dessus. Et les champs qui étaient en dessous des listes rouges ont disparus (groupe 2 INPN, etc.) mais du coup j'imagine en lien avec TaxHub?

**Comment by jpm-cbna** [comment]
@helenechauvin Pourrais tu essayer de rafraîchir ta page web, voir te déconnecter/reconnecter à GeoNature ? C'est surement du au fait que TaxHub ne fonctionnait pas quand tu as chargé ta page. De mon côté, j'ai bien tous les champs (voir ma capture ci-dessous).
Les requêtes fonctionne aussi sur les champs des statuts.

![Screenshot_20221124_140958](https://user-images.githubusercontent.com/51449363/203792540-56ad701f-8f71-4b27-9a7e-caaeea5b8f9f.jpg)

**Comment by helenechauvin** [comment]
@jpm-cbna Oui c'est tout bon maintenant. Merci !
