### ISSUE TITLE
[Mailing lists utilisateurs] Problème de mise à jour du mail actus@silene.eu

### ISSUE THREAD

**Issue by helenechauvin** [cbn-alpin/silene-geonature#217]
Je n'ai pas réussi à mettre à jour le mail actus@silene.eu alors que j'avais toujours réussi les autres fois. J'ai pu supprimer tous les mails présents mais l'import n'a pas fonctionné malgré plusieurs tentative, j'arrive à importer 500 mails sur les 1540 !

J'ai dû envoyé le mail d'actus par mail, mais ce n'est pas le plus pratique non plus car il y a une limite max de destinatires, donc plusieurs mails sont nécessaires.

Au vu de la procédure chronophage de la mise à jour de cette mailing list (même quand cela fonctionne), ne pourrait-on pas réfléchir à passer via une plateforme de newsletter type mailchimp (mais en version payante car on dépasse le quota de destinataire). Comment gérez-vous ce point côté Rhône-Alpes?

**Comment by okristo** [comment]
Peux-tu me transmettre le fichier d'import utilisé ?
Nous avons exactement la même problématique sur AURA. Nous réfléchissons à utiliser un outil de newsletter type Sendinblue (éventuellement Mailchimp mais retours plus mitigés en interne). Pour plusieurs raisons : 
- meilleure gestion des abonnés : une personne qui ne souhaite pas recevoir les actualités peut se désinscrire
- procédure ovh chronophage
- possibilité de mise en page offertes par ce type d'outil

**Comment by okristo** [comment]
La mailing-list a bien été mise à jour. J'ai du m'y reprendre à deux fois. Un message d'erreur ("une erreur est survenue lors de l'import"...) est apparu, j'ai ensuite renouvelé la manip d'import (sans supprimer les comptes déjà importés).
