### ISSUE TITLE
Zoom carte d'accueil

### ISSUE THREAD

**Issue by jmg-cbna** [cbn-alpin/silene-geonature#22]
Carte de l'accueil et de la synthèse : zoom sur la région PACA + limite région plus visible (comme dans atlas)

**Comment by jpm-cbna** [comment]
Ok, c'est noté.
A priori, c'est gérable via la configuration de GeoNature.

**Comment by jpm-cbna** [comment]
La carte est maintenant centré par défaut sur la région PACA.
Par contre, il n'est pas possible d'afficher la limite du territoire comme sur l'Atlas. Cela nécessite un développement pour le mettre en place.
Je ferme ce ticket mais si la limite de territoire s'avère nécessaire, nous pouvons ouvrir à nouveau ce ticket.

**Comment by jpm-cbna** [comment]
La possibilité d'afficher la limite du territoire et surement envisageable avec le mécanisme de couche sélectionnable en plus du fond de carte.
Il faudrait seulement ajouter un mécanisme permettant, via un paramètre de config, de sélectionner par défaut une couche.
