### ISSUE TITLE
[GeoNature] Problème utilisateur avec requête espèces

### ISSUE THREAD

**Issue by helenechauvin** [cbn-alpin/silene-geonature#220]
L'utilisateur n°20 (UsersHub) rencontre un problème d'accès aux données précises. Il a réalisé trois requêtes séparées pour « Pie-grièche écorcheur », « Pie-grièche méridionale » et « Criquet hérisson » sans filtre géographique. 

Il a essayé via Chrome puis via Mozilla, mais aucune donnée ne ressort, la requête mouline sans s'arrêter. 

Il a bien les droits d'accès et j'ai vérifié de mon côté, il y a tout au plus 10 000 données donc le facteur nombre d'observations n'est pas le point bloquant.

**Comment by okristo** [comment]
Peux-tu lui proposer ces deux actions : 
- se déconnecter et se reconnecter à Silene Expert
- vider le cache (CTRL + MAJ + R ou CTRL + F5)

Si le problème persiste, merci de lui demander des impressions d'écrans ainsi que la version de son navigateur (+ le système utilisé : Windows ou Linux)

**Comment by jpm-cbna** [comment]
Je confirme bien le problème sur son compte. J'ai supprimé ses vieux droits obsolète mais le problème est bien là.
Il y a 11 630 observations pour la recherche « Pie-grièche écorcheur » et la très grande majorité ne sont pas floutées...
Je me suis donné les mêmes droits sur mon compte "perso", je reproduis aussi le problème.
**Solution de contournement:** il est possible de faire fonctionner la requête en activant le mode "Mailles". Ce n'est pas le même affichage mais on peut exporter les résultats...

**Comment by jpm-cbna** [comment]
J'ai récupéré la requête qui échoue:
```sql
WITH "OBSERVATIONS" AS (
	SELECT DISTINCT ON (gn_synthese.v_synthese_for_web_app.id_synthese, gn_synthese.v_synthese_for_web_app.date_min) 
		gn_synthese.v_synthese_for_web_app.id_synthese AS id_synthese, 
		gn_synthese.v_synthese_for_web_app.id_nomenclature_diffusion_level AS id_nomenclature_diffusion_level, 
		gn_synthese.v_synthese_for_web_app.id_nomenclature_sensitivity AS id_nomenclature_sensitivity, 
		gn_synthese.v_synthese_for_web_app.st_asgeojson AS geojson
	FROM gn_synthese.v_synthese_for_web_app
		JOIN taxonomie.taxref 
			ON gn_synthese.v_synthese_for_web_app.cd_nom = taxonomie.taxref.cd_nom
	WHERE gn_synthese.v_synthese_for_web_app.the_geom_4326 IS NOT NULL
		AND taxonomie.taxref.cd_ref IN (3807)
	ORDER BY gn_synthese.v_synthese_for_web_app.date_min DESC
	LIMIT 100000
),
"PRIVATE_OBSERVATION" AS (
	SELECT DISTINCT ON ("OBSERVATIONS".id_synthese) 
		5000 AS priority, 
		"OBSERVATIONS".id_synthese AS id_synthese, 
		ref_geo.l_areas.geojson_4326 AS geojson
	FROM gn_synthese.cor_area_synthese
		JOIN ref_geo.l_areas 
			ON ref_geo.l_areas.id_area = gn_synthese.cor_area_synthese.id_area
		JOIN "OBSERVATIONS" 
			ON "OBSERVATIONS".id_synthese = gn_synthese.cor_area_synthese.id_synthese
	WHERE ref_geo.l_areas.id_type = 28
		AND "OBSERVATIONS".id_nomenclature_diffusion_level IN (136, 137, 138, 139)
),
"PRIVATE_OBSERVATION_PERM" AS (
	SELECT "PRIVATE_OBSERVATION".id_synthese AS id_synthese
	FROM "PRIVATE_OBSERVATION"
		JOIN gn_synthese.synthese 
			ON gn_synthese.synthese.id_synthese = "PRIVATE_OBSERVATION".id_synthese
		JOIN gn_synthese.cor_area_synthese 
			ON gn_synthese.cor_area_synthese.id_synthese = gn_synthese.synthese.id_synthese
		JOIN taxonomie.taxref 
			ON taxonomie.taxref.cd_nom = gn_synthese.synthese.cd_nom
	WHERE gn_synthese.synthese.id_nomenclature_diffusion_level IN (136, 137, 138, 139)
		AND gn_synthese.cor_area_synthese.id_area IN (34862, 34923)
), 
"SENSITIVE_OBSERVATION" AS (
	SELECT DISTINCT ON ("OBSERVATIONS".id_synthese) 10000 AS priority,
		"OBSERVATIONS".id_synthese AS id_synthese, 
		ref_geo.l_areas.geojson_4326 AS geojson
	FROM gn_synthese.cor_area_synthese
		JOIN ref_geo.l_areas 
			ON ref_geo.l_areas.id_area = gn_synthese.cor_area_synthese.id_area
		JOIN "OBSERVATIONS" 
			ON "OBSERVATIONS".id_synthese = gn_synthese.cor_area_synthese.id_synthese
	WHERE ref_geo.l_areas.id_type = 27
		AND "OBSERVATIONS".id_nomenclature_sensitivity IN (66, 67, 68)
),
"OBS_ALL" AS (
	SELECT 
		"PRIVATE_OBSERVATION".priority AS priority, 
		"PRIVATE_OBSERVATION".id_synthese AS id_synthese, 
		"PRIVATE_OBSERVATION".geojson AS geojson
	FROM "PRIVATE_OBSERVATION"
	WHERE NOT EXISTS (
		SELECT 'X' AS anon_1
		FROM "PRIVATE_OBSERVATION_PERM"
		WHERE "PRIVATE_OBSERVATION_PERM".id_synthese = "PRIVATE_OBSERVATION".id_synthese
	)
	UNION
	SELECT 
		"SENSITIVE_OBSERVATION".priority AS priority, 
		"SENSITIVE_OBSERVATION".id_synthese AS id_synthese, 
		"SENSITIVE_OBSERVATION".geojson AS geojson
	FROM "SENSITIVE_OBSERVATION"
	UNION 
	SELECT 
		1 AS priority, 
		"OBSERVATIONS".id_synthese AS id_synthese, 
		"OBSERVATIONS".geojson AS geojson
	FROM "OBSERVATIONS"
),
"BLURRED_OBSERVATIONS" AS (
	SELECT DISTINCT ON ("OBS_ALL".id_synthese)
		"OBS_ALL".id_synthese AS id_synthese, 
		"OBS_ALL".priority AS priority, 
		"OBS_ALL".geojson AS geojson, 
		json_build_object(
			'id', gn_synthese.v_synthese_for_web_app.id_synthese, 
			'date_min', gn_synthese.v_synthese_for_web_app.date_min, 
			'lb_nom', gn_synthese.v_synthese_for_web_app.lb_nom, 
			'cd_nom', gn_synthese.v_synthese_for_web_app.cd_nom, 
			'observers', gn_synthese.v_synthese_for_web_app.observers, 
			'dataset_name', gn_synthese.v_synthese_for_web_app.dataset_name, 
			'url_source', gn_synthese.v_synthese_for_web_app.url_source, 
			'unique_id_sinp', gn_synthese.v_synthese_for_web_app.unique_id_sinp, 
			'nom_vern_or_lb_nom', 
			COALESCE(NULLIF(gn_synthese.v_synthese_for_web_app.nom_vern, ''), gn_synthese.v_synthese_for_web_app.lb_nom), 
			'count_min_max', CASE 
					WHEN (gn_synthese.v_synthese_for_web_app.count_min != gn_synthese.v_synthese_for_web_app.count_max) 
						THEN concat(gn_synthese.v_synthese_for_web_app.count_min, ' - ', gn_synthese.v_synthese_for_web_app.count_max)
					WHEN (gn_synthese.v_synthese_for_web_app.count_min IS NOT NULL) 
						THEN concat(gn_synthese.v_synthese_for_web_app.count_min)
					ELSE '' 
				END
		) AS obs_as_json
	FROM "OBS_ALL"
		JOIN gn_synthese.v_synthese_for_web_app 
			ON gn_synthese.v_synthese_for_web_app.id_synthese = "OBS_ALL".id_synthese
	ORDER BY "OBS_ALL".id_synthese, "OBS_ALL".priority DESC
)
SELECT 
	"BLURRED_OBSERVATIONS".geojson, 
	json_build_object('observations', json_agg("BLURRED_OBSERVATIONS".obs_as_json)) AS json_build_object_1
FROM "BLURRED_OBSERVATIONS"
GROUP BY "BLURRED_OBSERVATIONS".geojson ;
```

Le problème est au niveau de la sous-requête de l'UNION `OBS_ALL` qui récupère les observations privées à flouter auxquelles nous retirons celles où l'utilisateur a des droits.
Celle-ci:
```sql
SELECT 
	"PRIVATE_OBSERVATION".priority AS priority, 
	"PRIVATE_OBSERVATION".id_synthese AS id_synthese, 
	"PRIVATE_OBSERVATION".geojson AS geojson
FROM "PRIVATE_OBSERVATION"
WHERE NOT EXISTS (
	SELECT 'X' AS anon_1
	FROM "PRIVATE_OBSERVATION_PERM"
	WHERE "PRIVATE_OBSERVATION_PERM".id_synthese = "PRIVATE_OBSERVATION".id_synthese
)
```
Elle met **10mn** à s'exécuter.
Du coup, j'ai  testé l'alternative suivante qui elle met **1,6s**:
```sql
SELECT 
	"PRIVATE_OBSERVATION".priority AS priority, 
	"PRIVATE_OBSERVATION".id_synthese AS id_synthese, 
	"PRIVATE_OBSERVATION".geojson AS geojson
FROM "PRIVATE_OBSERVATION"
WHERE "PRIVATE_OBSERVATION".id_synthese NOT IN (
	SELECT "PRIVATE_OBSERVATION_PERM".id_synthese
	FROM "PRIVATE_OBSERVATION_PERM"
)
```

Pour moi, elles ont la même signification et doivent fournir le même résultat. Je vais m'en assurer et essayer de comprendre pourquoi nous constatons une telle différence de temps d'exécution.

Ci-dessous les fichiers JSON des EXPLAIN de la requête posant problème avec l'utilisation de `NOT IN` et de `NOT EXISTS`:
  - `NOT IN`: [explain_not_in.txt](https://github.com/cbn-alpin/sinp-paca-tickets/files/12700599/explain_not_in.txt) et [sa représentation graphique](https://explain.dalibo.com/plan/3cg9233ge031761e)
  - `NOT EXISTS`: [explain_not_exists.txt](https://github.com/cbn-alpin/sinp-paca-tickets/files/12700654/explain_not_exists.txt) et [sa représentation graphique](https://explain.dalibo.com/plan/h5ag7fa6h1caadg9)

**Comment by jpm-cbna** [comment]
> J'ai récupéré la requête qui échoue:
> 
> ```sql
> WITH "OBSERVATIONS" AS (
> 	SELECT DISTINCT ON (gn_synthese.v_synthese_for_web_app.id_synthese, gn_synthese.v_synthese_for_web_app.date_min) 
> 		gn_synthese.v_synthese_for_web_app.id_synthese AS id_synthese, 
> 		gn_synthese.v_synthese_for_web_app.id_nomenclature_diffusion_level AS id_nomenclature_diffusion_level, 
> 		gn_synthese.v_synthese_for_web_app.id_nomenclature_sensitivity AS id_nomenclature_sensitivity, 
> 		gn_synthese.v_synthese_for_web_app.st_asgeojson AS geojson
> 	FROM gn_synthese.v_synthese_for_web_app
> 		JOIN taxonomie.taxref 
> 			ON gn_synthese.v_synthese_for_web_app.cd_nom = taxonomie.taxref.cd_nom
> 	WHERE gn_synthese.v_synthese_for_web_app.the_geom_4326 IS NOT NULL
> 		AND taxonomie.taxref.cd_ref IN (3807)
> 	ORDER BY gn_synthese.v_synthese_for_web_app.date_min DESC
> 	LIMIT 100000
> ),
> "PRIVATE_OBSERVATION" AS (
> 	SELECT DISTINCT ON ("OBSERVATIONS".id_synthese) 
> 		5000 AS priority, 
> 		"OBSERVATIONS".id_synthese AS id_synthese, 
> 		ref_geo.l_areas.geojson_4326 AS geojson
> 	FROM gn_synthese.cor_area_synthese
> 		JOIN ref_geo.l_areas 
> 			ON ref_geo.l_areas.id_area = gn_synthese.cor_area_synthese.id_area
> 		JOIN "OBSERVATIONS" 
> 			ON "OBSERVATIONS".id_synthese = gn_synthese.cor_area_synthese.id_synthese
> 	WHERE ref_geo.l_areas.id_type = 28
> 		AND "OBSERVATIONS".id_nomenclature_diffusion_level IN (136, 137, 138, 139)
> ),
> "PRIVATE_OBSERVATION_PERM" AS (
> 	SELECT "PRIVATE_OBSERVATION".id_synthese AS id_synthese
> 	FROM "PRIVATE_OBSERVATION"
> 		JOIN gn_synthese.synthese 
> 			ON gn_synthese.synthese.id_synthese = "PRIVATE_OBSERVATION".id_synthese
> 		JOIN gn_synthese.cor_area_synthese 
> 			ON gn_synthese.cor_area_synthese.id_synthese = gn_synthese.synthese.id_synthese
> 		JOIN taxonomie.taxref 
> 			ON taxonomie.taxref.cd_nom = gn_synthese.synthese.cd_nom
> 	WHERE gn_synthese.synthese.id_nomenclature_diffusion_level IN (136, 137, 138, 139)
> 		AND gn_synthese.cor_area_synthese.id_area IN (34862, 34923)
> ), 
> "SENSITIVE_OBSERVATION" AS (
> 	SELECT DISTINCT ON ("OBSERVATIONS".id_synthese) 10000 AS priority,
> 		"OBSERVATIONS".id_synthese AS id_synthese, 
> 		ref_geo.l_areas.geojson_4326 AS geojson
> 	FROM gn_synthese.cor_area_synthese
> 		JOIN ref_geo.l_areas 
> 			ON ref_geo.l_areas.id_area = gn_synthese.cor_area_synthese.id_area
> 		JOIN "OBSERVATIONS" 
> 			ON "OBSERVATIONS".id_synthese = gn_synthese.cor_area_synthese.id_synthese
> 	WHERE ref_geo.l_areas.id_type = 27
> 		AND "OBSERVATIONS".id_nomenclature_sensitivity IN (66, 67, 68)
> ),
> "OBS_ALL" AS (
> 	SELECT 
> 		"PRIVATE_OBSERVATION".priority AS priority, 
> 		"PRIVATE_OBSERVATION".id_synthese AS id_synthese, 
> 		"PRIVATE_OBSERVATION".geojson AS geojson
> 	FROM "PRIVATE_OBSERVATION"
> 	WHERE NOT EXISTS (
> 		SELECT 'X' AS anon_1
> 		FROM "PRIVATE_OBSERVATION_PERM"
> 		WHERE "PRIVATE_OBSERVATION_PERM".id_synthese = "PRIVATE_OBSERVATION".id_synthese
> 	)
> 	UNION
> 	SELECT 
> 		"SENSITIVE_OBSERVATION".priority AS priority, 
> 		"SENSITIVE_OBSERVATION".id_synthese AS id_synthese, 
> 		"SENSITIVE_OBSERVATION".geojson AS geojson
> 	FROM "SENSITIVE_OBSERVATION"
> 	UNION 
> 	SELECT 
> 		1 AS priority, 
> 		"OBSERVATIONS".id_synthese AS id_synthese, 
> 		"OBSERVATIONS".geojson AS geojson
> 	FROM "OBSERVATIONS"
> ),
> "BLURRED_OBSERVATIONS" AS (
> 	SELECT DISTINCT ON ("OBS_ALL".id_synthese)
> 		"OBS_ALL".id_synthese AS id_synthese, 
> 		"OBS_ALL".priority AS priority, 
> 		"OBS_ALL".geojson AS geojson, 
> 		json_build_object(
> 			'id', gn_synthese.v_synthese_for_web_app.id_synthese, 
> 			'date_min', gn_synthese.v_synthese_for_web_app.date_min, 
> 			'lb_nom', gn_synthese.v_synthese_for_web_app.lb_nom, 
> 			'cd_nom', gn_synthese.v_synthese_for_web_app.cd_nom, 
> 			'observers', gn_synthese.v_synthese_for_web_app.observers, 
> 			'dataset_name', gn_synthese.v_synthese_for_web_app.dataset_name, 
> 			'url_source', gn_synthese.v_synthese_for_web_app.url_source, 
> 			'unique_id_sinp', gn_synthese.v_synthese_for_web_app.unique_id_sinp, 
> 			'nom_vern_or_lb_nom', 
> 			COALESCE(NULLIF(gn_synthese.v_synthese_for_web_app.nom_vern, ''), gn_synthese.v_synthese_for_web_app.lb_nom), 
> 			'count_min_max', CASE 
> 					WHEN (gn_synthese.v_synthese_for_web_app.count_min != gn_synthese.v_synthese_for_web_app.count_max) 
> 						THEN concat(gn_synthese.v_synthese_for_web_app.count_min, ' - ', gn_synthese.v_synthese_for_web_app.count_max)
> 					WHEN (gn_synthese.v_synthese_for_web_app.count_min IS NOT NULL) 
> 						THEN concat(gn_synthese.v_synthese_for_web_app.count_min)
> 					ELSE '' 
> 				END
> 		) AS obs_as_json
> 	FROM "OBS_ALL"
> 		JOIN gn_synthese.v_synthese_for_web_app 
> 			ON gn_synthese.v_synthese_for_web_app.id_synthese = "OBS_ALL".id_synthese
> 	ORDER BY "OBS_ALL".id_synthese, "OBS_ALL".priority DESC
> )
> SELECT 
> 	"BLURRED_OBSERVATIONS".geojson, 
> 	json_build_object('observations', json_agg("BLURRED_OBSERVATIONS".obs_as_json)) AS json_build_object_1
> FROM "BLURRED_OBSERVATIONS"
> GROUP BY "BLURRED_OBSERVATIONS".geojson ;
> ```
> 
> Le problème est au niveau de la sous-requête de l'UNION `OBS_ALL` qui récupère les observations privées à flouter auxquelles nous retirons celles où l'utilisateur a des droits. Celle-ci:
> 
> ```sql
> SELECT 
> 	"PRIVATE_OBSERVATION".priority AS priority, 
> 	"PRIVATE_OBSERVATION".id_synthese AS id_synthese, 
> 	"PRIVATE_OBSERVATION".geojson AS geojson
> FROM "PRIVATE_OBSERVATION"
> WHERE NOT EXISTS (
> 	SELECT 'X' AS anon_1
> 	FROM "PRIVATE_OBSERVATION_PERM"
> 	WHERE "PRIVATE_OBSERVATION_PERM".id_synthese = "PRIVATE_OBSERVATION".id_synthese
> )
> ```
> 
> Elle met **10mn** à s'exécuter. Du coup, j'ai testé l'alternative suivante qui elle met **1,6s**:
> 
> ```sql
> SELECT 
> 	"PRIVATE_OBSERVATION".priority AS priority, 
> 	"PRIVATE_OBSERVATION".id_synthese AS id_synthese, 
> 	"PRIVATE_OBSERVATION".geojson AS geojson
> FROM "PRIVATE_OBSERVATION"
> WHERE "PRIVATE_OBSERVATION".id_synthese NOT IN (
> 	SELECT "PRIVATE_OBSERVATION_PERM".id_synthese
> 	FROM "PRIVATE_OBSERVATION_PERM"
> )
> ```
> 
> Pour moi, elles ont la même signification et doivent fournir le même résultat. Je vais m'en assurer et essayer de comprendre pourquoi nous constatons une telle différence de temps d'exécution.
> 
> Ci-dessous les fichiers JSON des EXPLAIN de la requête posant problème avec l'utilisation de `NOT IN` et de `NOT EXISTS`:
> 
> * `NOT IN`: [explain_not_in.txt](https://github.com/cbn-alpin/sinp-paca-tickets/files/12700599/explain_not_in.txt) et [sa représentation graphique](https://explain.dalibo.com/plan/3cg9233ge031761e)
> * `NOT EXISTS`: [explain_not_exists.txt](https://github.com/cbn-alpin/sinp-paca-tickets/files/12700654/explain_not_exists.txt) et [sa représentation graphique](https://explain.dalibo.com/plan/h5ag7fa6h1caadg9)

**Comment by jpm-cbna** [comment]
La correction a été mise en ligne.
