### ISSUE TITLE
Problème email automatique de réception de dépôt

### ISSUE THREAD

**Issue by yolanrichard** [cbn-alpin/silene-geonature#229]
L'email automatique normalement reçu par les administrateur de données lors d'un dépôt de jeu de données par une fournisseur ne fonctionne plus. Ayant fait le tour des gestionnaires des dépôts (Jean-Michel, Lucile, Mélodie, moi), aucun de nous ne recevons plus cet email, et nous ne sommes donc plus informés quand un nouveau dépôt a lieu. 
Cela a débuté mi-septembre (dernier email pour moi au 13/09).

**Comment by jpm-cbna** [comment]
Il y avait une mauvaise configuration du plugin d'envoi d'email de Wordpress.
Par ailleurs, il manquait l'activation de DMARC dans la zone DNS de silene.eu.
Voir la doc rédigé à cette occasion : https://wiki-sinp.cbn-alpin.fr/serveurs/installation/config-spf-dmarc-dkim
