### ISSUE TITLE
Demande de mot de passe oublié ne fonctionne pas

### ISSUE THREAD

**Issue by jpm-cbna** [cbn-alpin/silene-geonature#24]
La demande de renouvellement d'un mot de passe oublié ne fonctionne pas, l'interface affiche un "toaster" rouge contenant aucun texte.
![Screenshot_20200220_101943](https://user-images.githubusercontent.com/51449363/74919392-d4fbea80-53ca-11ea-87f7-ec5e77bc0d69.jpg)

**Comment by lvahe** [comment]
Test ce jour (car j'avais oublié le mien ...) : ça fonctionne !
