### ISSUE TITLE
Synthèse: accélérer le téléchargement

### ISSUE THREAD

**Issue by jpm-cbna** [cbn-alpin/silene-geonature#27]
L'export des données depuis la synthèse est relativement lent que l'on ait 100 ou 10 000 observations à exporter.

C'est apparemment dû à la création de jointure entre la table des nomenclatures et la table synthèse.

Une solution pour accélérer l'export, sans passer par du développement, consiste à supprimer les champs que nous jugeons inutiles. La liste des champs à garder dans l'export accessible via la synthèse est paramétrable.

@okristo @jmg-cbna Il serait intéressant de lister ici les champs que nous souhaitons garder pour que je puisse réaliser la modification de la configuration de GeoNature.

**Comment by okristo** [comment]
Difficile a priori de faire un tri dans les champs. On peut désactiver dans un premier temps tous les champs qui ne sont jamais remplis (voir dans les données CBNA et CEN PACA quels champs sont concernés)

**Comment by jpm-cbna** [comment]
Effectivement, nous pouvons vérifier les champs qui possèdent des données.
Mais par défaut, je propose de laisser les élémentaires qui répondent au qui, quoi, quand, où, plus les métadonnées essentielles soit:
- `permId`: UUID de l'observation.
- `permIdGrp`: UUID du relevé.
- `jddCode`: code du jeu de données.
- `validStat`: statut de validation.
- `validateur`: nom du validateur de l'observation.
- `observer`: Nom de l'observateur.
- `cdNom`: code TaxRef du nom.
- `nomCite`: nom scientifique d'origine donné à l'observation.
- `denbrMin`: Nombre minimum d'individus observés (pour la faune) => voir complétude.
- `denbrMax`: Nombre maximum d'individus observés (pour la faune) => voir complétude.
- `dateDebut`: Date de début de l'observation.
- `dateFin`: Date de fin de l'observation.
- `wkt`: géométrie de l'observation (coordonnées).
