### ISSUE TITLE
Utiliser des favicon distincts pour chaque appli

### ISSUE THREAD

**Issue by jpm-cbna** [cbn-alpin/silene-geonature#29]
Il serait utile de pouvoir distinguer les 3 sites (Silene Nature, Silene Expert et Silene "CMS") à l'aide de leur **favicon** seulement. C'est très pratique pour ceux qui épingle leurs onglets (à tester avec un clic droit sur un onglet de navigateur, puis sélectionner "Épingler cet onglet").

Un idée serait de remplacer la couleur de la partie droite du logo qui est en vers sur le logo par défaut. Une autre idée est d'utiliser un fond coloré à la place de la transparence actuelle. Qu'en pensez vous ?

**Comment by gkapfer** [comment]
Silene Nature : Logo tout vert – Silene – Nature SINP PACA
Silene Expert : Logo tout rose – Silene – Expert SINP PACA
Silene CMS = Logo actuel – Silene – SINP PACA

**Comment by gkapfer** [comment]
Je vais demander un logo à sonia. Est-ce qu'il y a une taille précise à fournir ou peu importe?

**Comment by jpm-cbna** [comment]
Alors, je viens de regarder ce site : https://realfavicongenerator.net/faq
Il s'avère que si l'on veut supporter plusieurs plateformes et navigateurs, il y a besoin de nombreuses images.
Mais, nous pouvons justement utiliser le site en question pour les générer.

Du coup, il faudrait juste pour chaque favicone une image PNG de 260x260px comme il le préconise. Nous utiliserons leur site pour générer les icônes. Sonia peut l'utiliser pour tester le résultat...

**Comment by lvahe** [comment]
@PaulCenPaca : Sonia a créé les logos demandés par Géraldine (voir son message du 1er sept), il faudrait donc les utiliser pour remplacer les favicons.
C'est en dehors de mes compétences donc penses-tu pouvoir t'en charger ? Dis-moi si tu as besoin que je t'envoie les éléments graphiques.
Merci !

**Comment by PaulCenPaca** [comment]
Pour le cms je peux le faire via wordpress. Pour expert et nature, il faut un accès au serveur pour remplacer les favicons exstants que je n'ai pas.

**Comment by jpm-cbna** [comment]
@PaulCenPaca Je me charge de le faire pour Expert et Nature.

**Comment by PaulCenPaca** [comment]
@jmg-cbna est-ce que tu veux ces images en 260x260 ? Je peux les redimensionner si tu veux.

![SILENE_favicon_violet](https://user-images.githubusercontent.com/33025268/99261232-b5d89f00-281c-11eb-894c-ba81deb619fa.png)
![SILENE_favicon_vert](https://user-images.githubusercontent.com/33025268/99261235-b6713580-281c-11eb-94a8-533334dd68f2.png)

**Comment by jpm-cbna** [comment]
@PaulCenPaca En fait, j'avais prévu d'utiliser le site que j'indique dans [un précédent commentaire](https://github.com/cbn-alpin/silene-geonature/issues/29#issuecomment-685744618). À partir des images 260x260, le site permet de génèrer tous les formats possibles.
Sans vouloir tout intégrer dans les sites, nous pouvons nous en servir pour récupérer des fichiers de favicon optimisés.

**Comment by jpm-cbna** [comment]
Favicon mis à jour pour Nature et Expert.
