### ISSUE TITLE
Création de compte : liste déroulante à remplacer

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#3]
En dessous de « j’ai lu et j’accepte la Charte » : liste déroulante « Exemple select ». A quoi servira-t-elle ?

**Comment by jpm-cbna** [comment]
Cette liste était là juste pour mettre en avant le fait qu'il est possible de configurer les champs que l'on souhaite sur ce formulaire.
Je vais la supprimer et remplacer ces champs par ce qui est prévu à la page 29 de [l'étude de préfiguration](https://geonature.fr/documents/2020-01-Etude-migration-PIFH-SILENE-GeoNature.pdf#page=29&zoom=auto,-218,643).

**Comment by jpm-cbna** [comment]
En cours d'intégration dans la pull-request PnX-SI/GeoNature#1044.
