### ISSUE TITLE
Revoir l'entête Silene Expert

### ISSUE THREAD

**Issue by gkapfer** [cbn-alpin/silene-geonature#30]
- [x] On retire l’image de fond.
- [x] Mise en place du logo SINP à la place du logo de la structure.
- [x] Lors du chargement de l'appli, à la place d'afficher "GeoNature" à droite du bouton d'ouverture/fermeture du menu principal,  il faudrait afficher "Accueil". 
- [x] Lorsque Sonia aura préparé un logo "SINP" amélioré de  64px de haut max et pas trop large pour rester visible, remplacer le logo "structure" dans l'entête.

**Comment by jpm-cbna** [comment]
Pour les images de l'entête, il pourrait être plus sympa d'avoir le logo SINP-SILENE (pour l'emplacement logo structure) mais aussi une image de fond qui pourrait s'afficher sur la droite du bandeau.
Un exemple: https://user-images.githubusercontent.com/23358384/81195909-b3200600-8fbe-11ea-9f35-a4dfa5badec0.png
