### ISSUE TITLE
Modification du texte d'accueil de Silene Nature

### ISSUE THREAD

**Issue by gkapfer** [cbn-alpin/silene-geonature#35]
Remplacer la première phrase par « Silene est la **plateforme régionale du SINP de Provence-Alpes-Côte d’Azur** qui a pour objectif **l’accès à l’information naturaliste pour tous**. Vous souhaitez connaître la répartition d’une espèce ou avoir la liste des espèces présente sur votre commune ou un territoire, **Silene Nature** vous permettra de découvrir en quelques clics la faune et la flore de votre région. »

**Comment by jpm-cbna** [comment]
Dans la première phrase sur le mot "**SINP**", ajouter un lien hypertexte pour renvoyer vers le site Internet de présentation du SINP : http://www.naturefrance.fr/sinp/presentation-du-sinp (Sonia R. - 2020-12-02)

Dans la deuxième phrase, supprimer le texte "_ou un territoire_".
