### ISSUE TITLE
Travailler la page Présentation de Silene Nature

### ISSUE THREAD

**Issue by gkapfer** [cbn-alpin/silene-geonature#38]
- [x] Si possible, remplacer le texte "Presentation Atlas" de l'infobulle qui s'affiche au survol de l'icône de point interrogation du menu de gauche (_sidebard_) par "Présentation Silene Nature"
- [x] Supprimer le contenu de la page en attendant 
- [ ] Travailler cette page (images et texte) = texte simpliste = liens vers CMS à chaque fois (@gkapfer et @lvahe)

**Comment by jpm-cbna** [comment]
Voici le doc avec le contenu pour la page de présentation de Silene Nature:
[Silene_Nature-GK.docx](https://github.com/cbn-alpin/silene-geonature/files/5673439/Silene_Nature-GK.docx)
