### ISSUE TITLE
Création de compte : problème e-mails

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#4]
Aucun e-mail reçu lors de la création de compte

**Comment by jpm-cbna** [comment]
Lors de la création du compte par l'utilisateur, ce dernier ne reçoit pas d'email. C'est l'administrateur qui en reçoit un lui demandant de valider le compte.
Par contre, lorsque l'administrateur valide le compte, aucun email n'est envoyé à l'utilisateur pour le prévenir que son compte et validé et ouvert.
Il me semble que c'est lors de la validation par l'administrateur que l'utilisateur devrait être notifié, non ? C'est ce qui était prévu dans [l'étude de préfiguration à la  page 29](https://geonature.fr/documents/2020-01-Etude-migration-PIFH-SILENE-GeoNature.pdf#page=31&zoom=auto,-218,767)

**Comment by jpm-cbna** [comment]
L'envoie d'email à l'utilisateur comme indiqué dans le commentaire précédent a été implémenté dans la pull-request PnX-SI/GeoNature#1036.

Pour en profiter cela nécessite une mise à jour de GeoNature et des applicatifs liés (voir #50).
