### ISSUE TITLE
Utiliser les photos de l'INPN sur Silene Nature

### ISSUE THREAD

**Issue by jpm-cbna** [cbn-alpin/silene-geonature#40]
Dans la section "À voir en ce moment", il serait intéressant de pouvoir afficher les photos issues de l'INPN.
- [ ] Vérifier si cette fonctionnalité existe dans GeoNature-Atlas au près de @camillemonchicourt et @TheoLechemia 
- [ ] Si absente, évaluer sa difficulté de réalisation et son intérêt

**Comment by camillemonchicourt** [comment]
On ne peut pas afficher dynamiquement les photos INPN dans des pages de GeoNature-atlas. 
Mais par contre, on a développé des scripts permettant d'importer les photos INPN, en se connectant au webservice Taxref depuis TaxHub. Voir https://github.com/PnX-SI/TaxHub/issues/150

Cela permet d'illustrer un GeoNature-atlas avec pas mal d'images de qualité et sous licence libre. Qui peuvent ensuite être complétées/remplacées par des photos locales.

**Comment by lvahe** [comment]
A vérifier auprès de @gkapfer  mais je pense que le but est celui que tu décris Camille : compléter la partie "A voir en ce moment" avec des photos (dont on ne dispose pas forcément dans nos bases icono) en se basant sur celles disponibles en libre chez l'INPN.

**Comment by jpm-cbna** [comment]
@lvahe  Oui, en effet. Comme ce n'est pas trop compliqué (merci @amandine-sahl), je vais lancer le script comme indiqué sur PnX-SI/TaxHub#150. Cela nous permettra de voir ce que cela donne...

**Comment by jpm-cbna** [comment]
@lvahe @gkapfer les photos sont en cours d'intégration, déjà 29 000 photos intégrés...

**Comment by jpm-cbna** [comment]
@camillemonchicourt faut il demander les droits d'utilisation des images de l'INPN ?
Selon le FAQ sur le site de l'INPN, ce n'est pas nécessaire sauf pour les images "Droits réservés".
Je ne sais pas ce qu'ils entendent par là mais pour l'instant sur les 30 000 photos intégrées, j'ai les licences suivantes:

```
Licence         Nombre de photos
CC BY	        75
CC BY-NC-ND	2
CC BY-SA	354
CC BY-NC-SA	30970
```
À part les 2 photos sous licence "BY-NC-ND", je pense que pour les autres c'est OK, non ?

**Comment by camillemonchicourt** [comment]
Non normalement c'est bon.
Justement ils ont ouvert cette API de leurs médias à notre demande, en n'incluant que les médias qui ont une licence CC BY. Les autres ne sont pas dans l'API. Donc c'est OK.
Par contre il faut bien veiller à afficher Auteur, source et licence dans leur usage, mais de mémoire c'est le cas dans GeoNature-atlas par défaut.

**Comment by jpm-cbna** [comment]
> Par contre il faut bien veiller à afficher Auteur, source et licence dans leur usage, mais de mémoire c'est le cas dans GeoNature-atlas par défaut.

Oui, c'est bien le cas, j'ai vérifié.
