### ISSUE TITLE
[CMS] Modifier bandeau haut CMS

### ISSUE THREAD

**Issue by lvahe** [cbn-alpin/silene-geonature#43]
Il faut remplacer le bandeau du haut de page actuel par le bandeau contenant le logo SINP. 
@jpm-cbna J'insère le nouveau bandeau dans la bibliothèque de médias CMS.

**Comment by lvahe** [comment]
@jpm-cbna @PaulCenPaca Il faut intégrer les nouveau bandeau avec le logo SINP (il est dans la bibliothèque de médias) et tester s'il s'adapte bien aux changements de taille d'écran. Si non, il faudra passer commande à Sonia d'un bandeau en plusieurs parties.

**Comment by PaulCenPaca** [comment]
J'ai fini mes travaux concernant le bandeau : Ajout du logo SINP sur les grandes résolutions, fabrication d'un bandeau intermédiaire avec la partie "bandes" raccourcie pour les petites résolutions et ajout du logo SINP à côté du logo Silene pour les smartphones.

**Comment by jpm-cbna** [comment]
Je viens de tester. C'est pas mal !

Par contre, si le fait que le logo SINP soit légèrement déformé avec certaines résolutions pose problème, il faudra voir si [la gestion de 2  images de fond distinctes](https://developer.mozilla.org/fr/docs/Web/CSS/CSS_Backgrounds_and_Borders/Utiliser_plusieurs_arri%C3%A8re-plans) ne résout pas le problème.

**Comment by lvahe** [comment]
@jpm-cbna @PaulCenPaca Est-ce que l'on peut considérer ce ticket comme clos ou attend-t-on validation du CoTech concernant le logo SINP un peu déformé ?

**Comment by PaulCenPaca** [comment]
J'ai fait des modifications vendredi pour pallier cette déformation.

**Comment by lvahe** [comment]
Ok, on verra si le Copil fait des remarques donc je ne clos pas ce ticket pour le moment.
Merci !

**Comment by lvahe** [comment]
@juliedelauge @gkapfer Pouvez-vous me confirmer que le rendu du bandeau du haut vous convient ? Merci !

**Comment by gkapfer** [comment]
Le bandeau est flou mais comme je sais que la def ne peut pas être bien meilleure, on va dire que c'est bon :) J'ai pas testé sur un smartphone...

**Comment by jpm-cbna** [comment]
@gkapfer @lvahe Un truc pour tester facilement l'affichage sur smartphone c'est d'utiliser un outil de test disponible sur les version de bureau de Firefox ou Chrome. [Cet article de blog décrit comment accéder à cet outil](https://www.objectifpapillon.fr/blog/5-methodes-simples-pour-tester-la-compatibilite-mobile-de-votre-site.html) dans la section 2.

**Comment by lvahe** [comment]
@gkapfer @juliedelauge Le rendu vous va ? On ferme ce ticket ?

**Comment by juliedelauge** [comment]
Ok pour moi

Julie DELAUGE
Adjointe à la Direction - Responsable Connaissance et Programmes
[cid:image001.jpg@01D6F32D.1933EE80]
CEN PACA
Nouvelle adresse : 18 avenue du Gand – 04200 Sisteron
Tél. 04 92 34 40 10
julie.delauge@cen-paca.org<mailto:julie.delauge@cen-paca.org>
www.cen-paca.org<http://www.cen-paca.org/>


De : lvahe <notifications@github.com>
Envoyé : vendredi 22 janvier 2021 10:37
À : cbn-alpin/silene-geonature <silene-geonature@noreply.github.com>
Cc : Julie Delauge <julie.delauge@cen-paca.org>; Mention <mention@noreply.github.com>
Objet : Re: [cbn-alpin/silene-geonature] [CMS] Modifier bandeau haut CMS (#43)


@gkapfer<https://github.com/gkapfer> @juliedelauge<https://github.com/juliedelauge> Le rendu vous va ? On ferme ce ticket ?
