### ISSUE TITLE
[CMS] Actualités : supprimer "posted in / by / on ..."

### ISSUE THREAD

**Issue by lvahe** [cbn-alpin/silene-geonature#44]
Dans l'onglet Ressources / Actualités, il faudrait supprimer les mentions "posted on" / "by + rédacteur" / "posted in Actus". L'idéal serait de n'avoir que le titre et la date de l'actu.

![github_actus](https://user-images.githubusercontent.com/64422654/91851210-15340380-ec5f-11ea-8dd6-b1d6bb565116.jpg)

**Comment by lvahe** [comment]
@PaulCenPaca peux-tu regarder si tu parviens à simplifier les titres des actus pour ne garder que le titre + la date ? 
Pour l'exemple en copie d'écran, il faudrait donc simplement avoir : " Silene, 1ère "plateforme régionale SINP" officiellement habilitée ! + 6 mai 2020".
Merci !

**Comment by PaulCenPaca** [comment]
C'est fait. Pour mémoire, j'ai édité le thème pour faire disparaître le libellé 'Posted on'. 
Apparence > Editeur de thème > inc > template-tags.php > $posted_on

**Comment by lvahe** [comment]
Merci @PaulCenPaca ! Je peux clore ce ticket ou faut-il intégré ta dernière remarque dans le Wiki ou autre pour traçabilité ?

**Comment by PaulCenPaca** [comment]
> Merci @PaulCenPaca ! Je peux clore ce ticket ou faut-il intégré ta dernière remarque dans le Wiki ou autre pour traçabilité ?

Tu peux clore
