### ISSUE TITLE
[CMS] Actualités : boucle de liens à corriger.

### ISSUE THREAD

**Issue by lvahe** [cbn-alpin/silene-geonature#45]
Depuis la page d'Accueil, on a accès aux 3 dernières actus. Quand on clique sur le titre d'une actu ou sur "Lire la suite", on arrive sur une page qui détaille toute l'actu. En bas de cette page nouvelle, il y a la possibilité de cliquer sur "Posted in Actus" et on arrive sur une nouvelle page intitulée "Catégories : Actus". Cette boucle de liens n'est pas voulue et pas mal confuse. D'où vient cette page "Catégories : Actus" ?

On peut accéder aux actualités par un autre chemin (voulu celui-ci) : Ressource / Actualités. Cet accès est à conserver, ainsi que les dernières actus sur l'accueil.

**Comment by lvahe** [comment]
@PaulCenPaca Peux-tu regarder cela ?
Merci !

**Comment by PaulCenPaca** [comment]
La page https://cms.silene.eu/category/actus/ regroupe tous les articles étiquetés "Actus", ce qui a son utilité. Je suppose que faire disparaître le "Posted in Actus" serait suffisant ?

**Comment by lvahe** [comment]
Je ne suis pas sûre de comprendre ta question ...

**Comment by jpm-cbna** [comment]
@PaulCenPaca J'essaye de garder une trace de la configuration du CMS dans [une page dédié du wiki](https://wiki-sinp.cbn-alpin.fr/serveurs/sinp-paca/cms-theme). Pourrais tu y indiquer succinctement les modifications que tu as faites ?
Tu verras que j'y ai aussi copier/coller le CSS ...

**Comment by lvahe** [comment]
Le souci semble être corrigé, @jpm-cbna @PaulCenPaca vous me confirmez que l'on peut clore ce ticket ?
Merci !
