### ISSUE TITLE
Boutons d'accès à GN : ouverture dans un nouvel onglet

### ISSUE THREAD

**Issue by lvahe** [cbn-alpin/silene-geonature#46]
Les (magnifiques !) boutons "Accéder à Silene Nature" et "Accéder à Silene Expert" permettent d'accéder aux outils en ouvrant les liens dans l'onglet actif. 
Il faudrait modifier cela pour que les liens vers les outils GN s'ouvrent dans un nouvel onglet et non pas dans l'onglet actif. 
Ces boutons sont présents sur la page "Accueil" et sur la page "Données".

**Comment by jpm-cbna** [comment]
Deux solutions:
- soit le lien est géré via Wordpress, dans ce cas il faut chercher l'option dans les parmètres du liens qui permet de réaliser une ouverture dans un autre onglet.
- soit le lien est en HTML, dans ce cas là, il suffit d'ajouter l'attribut `target="_blank"` à la balise `<a>`. Ex. : `<a href="..." target="_blank">`

@lvahe peux tu voir si tu y arrives avec ces infos ?

**Comment by lvahe** [comment]
Done ! Merci !
