### ISSUE TITLE
Page adhérents : logos + liens hypertexte

### ISSUE THREAD

**Issue by lvahe** [cbn-alpin/silene-geonature#48]
Sur la page "Adhérents", est-il possible de rendre les logos des partenaires "cliquables" pour arriver sur les sites internet des partenaires ? 
Exemple : on clique sur le logo CEN PACA et on arrive sur le site internet du CEN PACA.

@gkapfer : est-ce vraiment indispensable ? Selon la faisabilité de la manipulation, cela peut être très chronophage car il y 80 structures (peut être pas autant de sites internet, mais ça fait quand même beaucoup).

@jpm-cbna : quid du suivi de la pérennité des liens en question, quand une structure abandonne son site internet ou en change, par exemple ... ?

**Comment by jpm-cbna** [comment]
Pour la pérennité des liens, il n'y a pas d'autre solution que de les tester... Ceci dit une structure qui a son propre nom de domaine ne devrait pas en changer souvent (jamais à mon avis). Du coup, si on ne met que les liens avec nom de domaine propre et qui pointe sur la page d'accueil (Ex. : https://www.cbn-alpin.fr/), cela devrait aller.

**Comment by jpm-cbna** [comment]
Pour l'ajout des liens, avec le modèle où l'image est gérée par Wordpress, c'est relativement simple.
Il suffit de cliquer sur l'image, puis sur l'icône de maillon de chaine:
1. - saisir l'adresse web du site.
2. - cliquer ensuite sur l'icône de flèche vers le bas pour ouvrir la gestion avancée du lien et activer l'option du lien "_Ouvrir dans un nouvel onglet_".

**Comment by jpm-cbna** [comment]
Dernier point, l'ajout de liens pertinents vers des sites externes renforce l'indexation naturelle d'un site par les moteurs de recherche.
Même si c'est une tâche fastidieuse, ce n'est pas du temps de perdu...

**Comment by lvahe** [comment]
C'est fait pour les 3 conservatoires. Par contre, je n'ai pas compris mais le logo CEN PACA était en HTML et je n'ai pas réussi à le modifier visuellement : quand je cliquais sur les 3 petites points, il n'y avait pas l'option "Modifier visuellement".
Du coup, j'ai dupliqué le bloc CBNA, remplacé l'image qui était en mode visuel et changer le texte (puis supprimé le bloc qui posait problème). 
@gkapfer je vais créer un tuto dans le Wiki SINP pour la modification de cette page (à moins que l'on puisse créer une note dans l'admin de Wordpress et visible par tous ? @jpm-cbna ) . Ce n'est pas compliqué mais les options proposées par Wordpress ne permettaient pas d'arriver à se résultat, Jean-Pascal a donc fait des ajouts en HTML. Il faut simplement penser a bien réutiliser les blocs existants pour garder la mise en forme sans repasser par le HTML.
