### ISSUE TITLE
Accueil : affichage des 100 dernières observations

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#5]
En page d'accueil, l'affichage des 100 dernières observations ne me paraît pas pertinent. Il serait préférable, à mon sens, d'afficher les 50 000 dernières observations comme c'est le cas dans la synthèse (cf. copie écran).
![GN_synthese](https://user-images.githubusercontent.com/61181043/74727899-25940c00-5242-11ea-97b7-eef9f26b4379.jpg)

**Comment by jpm-cbna** [comment]
Pourquoi pas, mais ta synthèse affiche par défaut les 50 000 dernières observations ? Moi, de mon côté c'est limité au 100 dernières...

Si on affiche 50 000 observations sur la carte de la page d'accueil, il faut avoir conscience que cela peut charger le serveur avec une requête lourde réaliser très régulièrement par tous les utilisateurs qui se connectent.

Il faut réaliser un test pour voir s'il y a des mécanismes de cache en place qui limite la charge du serveur.

**Comment by jpm-cbna** [comment]
Après vérification, il n'y a pas de paramétrage possible pour le module "100 dernières obs" de la page d'accueil. Il est seulement possible de l'afficher ou pas.

Toutefois, c'est relativement facile de rajouter des paramètres.

**Comment by jpm-cbna** [comment]
Nous n'affichons pas la carte au final.
Elle nécessiterait des développement supplémentaires pour pouvoir être intégré dans notre cas.
