### ISSUE TITLE
Accueil : nombre de jeux de données

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/silene-geonature#6]
Dans les stats affichées, le nombre de jeux de données est de 0 alors qu'il y a deux jeux de données intégrés

**Comment by jpm-cbna** [comment]
De mon côté, le nombre indiqué est de "1". Ce chiffre semble logique car le 2nd jeu de données (lié à mon compte) est vide. Du coup, cela n'affiche que le nombre de jeux de données possédant des observations.

Peux tu regarder si le chiffre est toujours à "0" de ton côté. Si c'est le cas, c'est surement lié au droit de ton compte utilisateur.

**Comment by jpm-cbna** [comment]
Je viens de regarder à nouveau ce matin avec un utilisateur qui a les même droits que toi. J'ai aussi le chiffre 0.

Le problème correspond au [bug #752 de GeoNature](https://github.com/PnX-SI/GeoNature/issues/752). @TheoLechemia vient de le corriger.

Je ferme donc ce ticket.
