### ISSUE TITLE
Intégration des utilisateurs et organismes

### ISSUE THREAD

**Issue by jpm-cbna** [cbn-alpin/silene-geonature#60]
Migrer les informations des utilisateurs et organismes de l'ancien système au nouveau.

Pour la migration des organismes:
- [ ] voir s'il est possible de se baser sur [le référentiel organisme de l'INPN](https://inpn.mnhn.fr/telechargement/referentiels/organismes).
- [ ] définir comment exporter les informations des organismes depuis l'outil Silene actuel

Pour la migration des utilisateurs, deux possibilités existent: 
- réinscription individuelle des utilisateurs depuis les interfaces de GeoNature
- migration des données depuis l'outil Silene actuel (à étudier si faisable: problème des mots de passe, pas de vrai compte utilisateur...)

Cela nécessite de faire un choix.

**Comment by jpm-cbna** [comment]
Finalement, les utilisateurs devront se réinscrire sur GeoNature.
Pas de gestion des organismes pour l'instant ou alors manuelle... Dans ce cas là, se baser [sur le standard](https://inpn.mnhn.fr/telechargement/referentiels/organismes) pour les créer.

**Comment by juliedelauge** [comment]
Nous avons un référentiel « organismes » on peut s’en servir, non ?
Julie


[cid:564d6165-6681-4ef6-ac7e-9db424007842]<http://www.cen-paca.org/index.php?rub=0>​

 [cid:30ce1ba6-cf9d-4098-bcd0-1af0a5508258] <https://www.facebook.com/CENPACA/>   [cid:a68c290e-8b4d-4f64-b1c6-e438422bdc67] <https://www.instagram.com/cen_paca/?hl=fr>
Julie DELAUGE
Adjointe à la Direction –
Responsable Connaissance et Programmes
Conservatoire d'espaces naturels de Provence-Alpes-Côte d'Azur
18 avenue du Gand – 04200 Sisteron
Tél. 04 92 34 40 10
julie.delauge@cen-paca.org - www.cen-paca.org<http://www.cen-paca.org>

[cid:e8790ea2-a3b9-460d-a37a-9d6d61750590]<https://www.helloasso.com/associations/conservatoire-d-espaces-naturels-de-provence-alpes-cote-d-azur/adhesions/adhesion-2021-au-conservatoire-d-espaces-naturels-de-provence-alpes-cote-d-azur>


De : Jean-Pascal Milcent <notifications@github.com>
Envoyé : jeudi 4 mars 2021 11:00
À : cbn-alpin/silene-geonature <silene-geonature@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [cbn-alpin/silene-geonature] Intégration des utilisateurs et organismes (#60)


Finalement, les utilisateurs devront se réinscrire sur GeoNature.
Pas de gestion des organismes pour l'instant ou alors manuelle... Dans ce cas là, se baser sur le standard<https://inpn.mnhn.fr/telechargement/referentiels/organismes> pour les créer.
