### ISSUE TITLE
[CMS] Gestion droits photos

### ISSUE THREAD

**Issue by lvahe** [cbn-alpin/silene-geonature#69]
Faire le point avec CEN PACA concernant les droits des photos sur le CMS : que met-on et où ?

**Comment by lvahe** [comment]
@gkapfer @juliedelauge Que souhaitez-vous faire apparaitre sous les photos : nom de l'auteur + CEN PACA ? CEN PACA seul ?

**Comment by juliedelauge** [comment]
nom de l'auteur + CEN PACA

Julie DELAUGE
Adjointe à la Direction - Responsable Connaissance et Programmes
[cid:image001.jpg@01D6EB44.07815BF0]
CEN PACA
Nouvelle adresse : 18 avenur du Gand – 04200 Sisteron
Tél. 04 92 34 40 10
julie.delauge@cen-paca.org<mailto:julie.delauge@cen-paca.org>
www.cen-paca.org<http://www.cen-paca.org/>


De : lvahe <notifications@github.com>
Envoyé : lundi 14 décembre 2020 16:18
À : cbn-alpin/silene-geonature <silene-geonature@noreply.github.com>
Cc : Julie Delauge <julie.delauge@cen-paca.org>; Mention <mention@noreply.github.com>
Objet : Re: [cbn-alpin/silene-geonature] [CMS] Gestion droits photos (#69)


@gkapfer<https://github.com/gkapfer> @juliedelauge<https://github.com/juliedelauge> Que souhaitez-vous faire apparaitre sous les photos : nom de l'auteur + CEN PACA ? CEN PACA seul ?

**Comment by lvahe** [comment]
@gkapfer @juliedelauge Je vous laisse vérifier que toutes les photos sont bien de Sonia Richaud. Merci !
