### ISSUE TITLE
[CMS] Compléter la page adhérents

### ISSUE THREAD

**Issue by lvahe** [cbn-alpin/silene-geonature#86]
Il faut compléter la page _Adhérents_ en intégrant les logos + description de chaque adhérent à Silene.

**Comment by PaulCenPaca** [comment]
J'ai complété la page avec les textes et logos que j'avais à disposition. Mais il en manque encore pas mal et bon nombre d'organismes n'ont pas joué le jeu des 300 caractères maximum...

**Comment by gkapfer** [comment]
Ensemble des adhérents sont listés - liste des adhérents aussi
