### ISSUE TITLE
Haut de page d'acceuil Silene Expert

### ISSUE THREAD

**Issue by juliedelauge** [cbn-alpin/silene-geonature#98]
Peut-on mettre le logo silene quelque part e page d'accueil de Silene Expert et insérer le bandeau de lacharte graphique en haut, elle est très monotone et triste cette page d’accueil.

**Comment by jpm-cbna** [comment]
Pour le logo Silene Expert, c'est corrigé. Une évolution du code de GeoNature dans la dernière version avait entraîné sa disparition. Ce logo est maintenant dans la partie personnalisable de l'interface de GeoNature. Il ne devrait plus sauter.

Pour le bandeau de la chartre graphique à insérer dans l'entête, ce n'est pas évidant et le sujet a déjà été discuté. J'avais à l'origine fait une proposition avec une image de fond reprenant ce bandeau. Il a été retiré comme demandé (voir #30). Si l'on souhaite l'intégrer, il me faut une image avec des couleurs assez douce pour que le texte reste visible. Voir mon commentaire à ce sujet qui contient un lien vers un exemple : https://github.com/cbn-alpin/silene-geonature/issues/30#issuecomment-707620045

**Comment by juliedelauge** [comment]
C’est bien ce qu’il me semblait et je ne l’ai pas retrouvé…désolée
On te prépare quelque chose pour test

Julie DELAUGE
Adjointe à la Direction - Responsable Connaissance et Programmes
[cid:image001.jpg@01D6EDB2.DEAC8C60]
CEN PACA
Nouvelle adresse : 18 avenue du Gand – 04200 Sisteron
Tél. 04 92 34 40 10
julie.delauge@cen-paca.org<mailto:julie.delauge@cen-paca.org>
www.cen-paca.org<http://www.cen-paca.org/>


De : Jean-Pascal Milcent <notifications@github.com>
Envoyé : lundi 18 janvier 2021 15:56
À : cbn-alpin/silene-geonature <silene-geonature@noreply.github.com>
Cc : Julie Delauge <julie.delauge@cen-paca.org>; Author <author@noreply.github.com>
Objet : Re: [cbn-alpin/silene-geonature] Haut de page d'acceuil Silene Expert (#98)


Pour le logo Silene Expert, c'est corrigé. Une évolution du code de GeoNature dans la dernière version avait entraîné sa disparition. Ce logo est maintenant dans la partie personnalisable de l'interface de GeoNature. Il ne devrait plus sauter.

Pour le bandeau de la chartre graphique à insérer dans l'entête, ce n'est pas évidant et le sujet a déjà été discuté. J'avais à l'origine fait une proposition avec une image de fond reprenant ce bandeau. Il a été retiré comme demandé (voir #30<https://github.com/cbn-alpin/silene-geonature/issues/30>). Si l'on souhaite l'intégrer, il me faut une image avec des couleurs assez douce pour que le texte reste visible. Voir mon commentaire à ce sujet qui contient un lien vers un exemple : #30 (comment)<https://github.com/cbn-alpin/silene-geonature/issues/30#issuecomment-707620045>

**Comment by jpm-cbna** [comment]
J'ai remis le logo Silene Expert qui avait "sauté" suite à une modification du code de GeoNature dans la dernière version. La modification visait à placer ce logo dans le dossier des éléments personnalisables de GeoNature. Cela simplifie sa gestion à l'avenir.

Pour le bandeau de la charte graphique, j'avais fait une proposition à l'origine avec une image de fond. Je l'ai retiré suite à une demande (voir #30). Pour le réintégrer, il faudrait me fournir une image avec des couleurs pas trop foncées pour que le texte du bandeau reste lisible. Voir mon commentaire contenant un exemple : https://github.com/cbn-alpin/silene-geonature/issues/30#issuecomment-707620045

**Comment by jpm-cbna** [comment]
Taille de l'image de fond 64px de haut, 750px de large.

**Comment by jpm-cbna** [comment]
Les contraintes techniques ont été vues ce jour avec Sonia qui va proposer une nouvelle image.

Celle-ci posant trop de difficultés pour l'intégrer proprement dans le bandeau:
![Bandeau_Silene_site_V4-01](https://user-images.githubusercontent.com/51449363/107037292-28716f00-67bb-11eb-9a8d-fee8909d9e4e.png)
