### ISSUE TITLE
Silene-Expert vocabulaire permissions et accès

### ISSUE THREAD

**Issue by juliedelauge** [cbn-alpin/silene-geonature#99]
Sur l'interface de Silene-Expert dans le profil utilisateur il est noté  « demander une permission » mais en fait c’est une demande d’accès aux données j’ai l’impression que le vocabulaire entre ce formulaire et celui employé dans l’interface d’administration n’est pas cohérent : 
-	la "demande de permission" est traitée par l’interface « Gestion des demande d'accès » puisque c’est un paramétrage des droits d' accès
-	l’inscription est gérée par l’interface Administration des permissions qui gère les droits aux fonctionnalités
Donc dans le profil utilisateur « demander une permission » devrait être renommer « demander un accès aux données »

**Comment by jpm-cbna** [comment]
Ok. Changement prise en compte dans la prochaine version.

**Comment by juliedelauge** [comment]
ce ci n' a pas été fait partout, il faudrait aussi changer le titre du formulaire et ne pas parler de "permissions"
"Demande de permissions d'accès" à changer par "demande d'accès aux données" idem dans le message après enregistrement de la demande, je voulais regarder le mails reçu par le demandeur mais je ne peux pas valider ma demande...pas d'accès pour l'instant

**Comment by jpm-cbna** [comment]
Ok, les titres du formulaire ont été mis à jour.
Le contenu des emails à destination des utilisateurs aussi.
